[package]
name = "lotr-mod-discord-bot"
version = "0.1.0"
authors = ["AldanTanneo <aldantanneo@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
bytesize = "1.0"
itertools = "0.10"
reqwest = "0.11"
serde_json = "1.0"
serde = "1.0"
rand = "0.8"
mysql_async = "0.28"
chrono = "0.4"
humantime-serde = "1.0.1"
dashmap = "4.0"

[dependencies.tokio]
version = "1.9"
features = [
    "macros", 
    "rt-multi-thread"
]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "cache",
    "unstable_discord_api"
]
