[package]
name = "lotr-mod-discord-bot"
version = "0.1.0"
authors = ["AldanTanneo <aldantanneo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0.1", features = ["macros", "rt-multi-thread"] }
itertools = "0.10.0"
mysql_async = "0.25.0"
reqwest = "0.11.0"
serde_json = "1.0.59"
serde = "1.0.118"
rand = "0.8.1"
search_with_google = { git = "https://gitlab.com/AldanTanneo/search-with-google" }
sys-info = "0.7.0"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]
version = "0.10.1"