[package]
name = "lotr-mod-discord-bot"
version = "0.1.0"
authors = ["AldanTanneo <aldantanneo@gmail.com>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
bytesize = "1.1"
itertools = "0.10"
reqwest = "0.11"
serde_json = "1.0"
serde = "1.0"
rand = "0.8"
chrono = "0.4"
humantime-serde = "1.0"
dashmap = "5.0"
alea = "0.2"

[dependencies.mysql_async]
version = "0.29"

[dependencies.mysql_common]
version = "0.28"
features = [ "chrono" ]

[dependencies.tokio]
version = "1.15"
features = [
    "macros", 
    "rt-multi-thread",
    "signal"
]

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "cache",
    "unstable_discord_api",
    "collector"
]
