[package]
name = "lotr-mod-discord-bot"
version = "0.1.0"
authors = ["AldanTanneo <aldantanneo@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
bytesize = "1.0"
itertools = "0.10"
reqwest = "0.11"
serde_json = "1.0"
serde = "1.0"
rand = "*"
mysql_async = "0.27"
chrono = "0.4"

[dependencies.async-minecraft-ping]
git = "https://github.com/AldanTanneo/async-minecraft-ping"

[dependencies.tokio]
version = "1.6"
features = [
    "macros", 
    "rt-multi-thread"
]

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
    "cache"
]
version = "0.10.7"
