name: Fly Deploy

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "Cargo.toml"

jobs:
  check:
    uses: ./.github/workflows/rust.yml
  deploy:
    name: Deploy app
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
