name: Rust workflow

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo fmt
        run: cargo fmt --check
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - name: Run cargo check
        run: cargo check
