name: Rust workflow

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "Cargo.toml"
  pull_request:
    branches: [main]
    paths:
      - "src/*"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
