name: Rust

on:
  push:
    branches: [ main ]
    paths: 
      - "src/**"
      - "Cargo.toml"
  pull_request:
    branches: [ main ]
    paths: 
      - "src/*"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check
      run: cargo check
